### ISSUE TITLE
The built-in microphone is not working - Dell Chromebook 11 2-in-1 (3189) KEFKA 2017 Intel Braswell

### ISSUE THREAD

**Issue by twisteros** [WeirdTreeThing/chromebook-linux-audio#84] opened 2024-01-20 11:25 UTC
**Describe the bug**
The built-in microphone doesn't pick up sounds. When I turn recording pn and play it back I usually hear 1 or 2 cracks and nothing more. Just silence. When I tap the touchpad mixer shows signal as microphone was picking sounds. When it happens the signal bar goes to the maximum and immediately gets back to minimum. There is some delay between tapping and the signal bar.

**Boardname**
Kefka 

Dell Chromebook 11 2-in-1 (3189) KEFKA 2017 Intel Braswell

**Logs**
Generate logs with `wget https://raw.githubusercontent.com/chrultrabook/linux-tools/main/debugging.sh; bash debugging.sh` and attach the output here.

A script debugging.sh is reporting missing lspci even though pciutils package is already installed (proof below).

> $ sudo ./debugging.sh 
> Welcome.
> This script will ask you for sudo password, which is necessary to extract required information.
> --2024-01-20 12:18:37--  https://mrchromebox.tech/files/util/cbmem.tar.gz
> Resolving mrchromebox.tech (mrchromebox.tech)... 198.100.145.128
> Connecting to mrchromebox.tech (mrchromebox.tech)|198.100.145.128|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 21705 (21K) [application/octet-stream]
> Saving to: ‘cbmem.tar.gz’
> 
> cbmem.tar.gz                         100%[===================================================================>]  21.20K  --.-KB/s    in 0.001s  
> 
> 2024-01-20 12:18:38 (33.0 MB/s) - ‘cbmem.tar.gz’ saved [21705/21705]
> 
> Failed to connect to bus: No medium found
> Failed to connect to bus: No medium found
> Failed to connect to bus: No medium found
> Failed to connect to bus: No medium found
> Failed to connect to bus: No medium found
> Failed to connect to bus: No medium found
> lspci not found. Please install pciutils.
> Log collection done.
> Please upload "debug-logs.tar.gz" for analysis.
> me@home-book:~/Documents/mic-issue
> $ lspci
> 00:00.0 Host bridge: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series SoC Transaction Register (rev 35)
> 00:02.0 VGA compatible controller: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Integrated Graphics Controller (rev 35)
> 00:10.0 SD Host controller: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series MMC Controller (rev 35)
> 00:12.0 SD Host controller: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series SD Controller (rev 35)
> 00:14.0 USB controller: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series USB xHCI Controller (rev 35)
> 00:1b.0 Audio device: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series High Definition Audio Controller (rev 35)
> 00:1c.0 PCI bridge: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCI Express Port #1 (rev 35)
> 00:1c.2 PCI bridge: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCI Express Port #3 (rev 35)
> 00:1f.0 ISA bridge: Intel Corporation Atom/Celeron/Pentium Processor x5-E8000/J3xxx/N3xxx Series PCU (rev 35)
> 02:00.0 Network controller: Intel Corporation Wireless 7265 (rev 61)

**Comment by WeirdTreeThing** [comment] 2024-01-20 13:37
Duplicate of #76

**Closed by WeirdTreeThing** 2024-01-20 13:37 UTC
