### ISSUE TITLE
python throwing error about urlretrieve when trying to run setup-audio on asus c434t running alpine linux 3.20.2

### ISSUE THREAD

**Issue by ThatOneChicken1** [WeirdTreeThing/chromebook-linux-audio#164] opened 2024-08-23 01:38 UTC
I'm trying to use this script to enable audio on my asus c434t running alpine linux, which seems to be supported. When I try to run the script, python throws an error about urlretrieve and the script stops. The full output is below

WARNING: You may run into audio issues, even after running this script. Please report any issues on github.
Installing AVS
Installing topology
Traceback (most recent call last):
  File "/home/chkn/chromebook-linux-audio/./setup-audio", line 319, in <module>
    match_platform(board)
  File "/home/chkn/chromebook-linux-audio/./setup-audio", line 95, in match_platform
    avs_audio()
  File "/home/chkn/chromebook-linux-audio/./setup-audio", line 151, in avs_audio
    urlretrieve(url=avs_tplg_url, filename="/tmp/avs_tplg/avs-tplg.tar.gz")
  File "/usr/lib/python3.12/urllib/request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

I tried installing urllib with apk (the package py3-urllib3 specifically) and this did not change anything. How can I fix this? Do I have to manually install the packages?

**Comment by koluckirafal** [comment] 2024-08-23 16:26
Duplicate of #159, see comments there for workarounds.

**Comment by ThatOneChicken1** [comment] 2024-08-23 19:44
That worked. Thanks!

**Closed** 2024-08-23 19:44 UTC
