### ISSUE TITLE
audio not working on kano based on raptorlake

### ISSUE THREAD

**Issue by gxsw** [WeirdTreeThing/chromebook-linux-audio#39] opened 2023-10-06 19:56 UTC
Hi!
I ran the script on a new kano (Acer Chromebook Spin 714) based on raptorlake. The script ran successfully, but audio was not working after reboot (archlinux). Could this be, because kano initially was based on alderlake and the script is considering kano as alderlake? Thx

**Comment by WeirdTreeThing** [comment] 2023-10-06 20:10
Raptorlake and Alderlake are similar enough that it should work the same. Can you run [this script](https://chrultrabook.github.io/docs/docs/debugging.html#acpi-and-linux-kernelspace) and upload the file it creates.

**Comment by gxsw** [comment] 2023-10-06 20:20
Thank you for your quick feedback. I attached the debug file
[debug-logs.tar.gz](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/12835226/debug-logs.tar.gz)

**Comment by WeirdTreeThing** [comment] 2023-10-06 21:28
Turns out there is a significant difference between Alderlake and Raptorlake, a fix should be out soon.

**Comment by WeirdTreeThing** [comment] 2023-10-06 22:37
I just pushed an update to the script. Run it again and let me know if it works.

**Comment by gxsw** [comment] 2023-10-07 08:00
Thank you so much for you quick support!
Running the new script I get this error:

[archlinux chromebook-linux-audio]$ ./setup-audio 
WARNING: this audio script is not fully functional yet!
Installing SOF
Installing SOF firmware
warning: sof-firmware-2023.09-1 is up to date -- skipping
warning: linux-firmware-20230804.7be2766d-2 is up to date -- skipping
warning: alsa-utils-1.2.10-1 is up to date -- skipping
Traceback (most recent call last):
  File "/home/hns/chromebook-linux-audio/./setup-audio", line 303, in <module>
    sof_audio(boards[device_board])
  File "/home/hns/chromebook-linux-audio/./setup-audio", line 159, in sof_audio
    for tplg in tplg:
                ^^^^
UnboundLocalError: cannot access local variable 'tplg' where it is not associated with a value

**Comment by WeirdTreeThing** [comment] 2023-10-07 10:55
Fixed, try again.

**Comment by gxsw** [comment] 2023-10-07 12:56
You are awesome! It is working now. Thx!
With your chromebook audio project you are doing an amasing job for the community.
Do you have paypal address where I can send a donation to?

P.S.: Whats not yet working on my kano is the built-in camera. I would be glad for anything you can point me to to get it fixed ;)

**Comment by WeirdTreeThing** [comment] 2023-10-07 13:43
> With your chromebook audio project you are doing an amasing job for the community.
Do you have paypal address where I can send a donation to?

Thanks, I appreciate it. Send me an email to weirdtreething@chrultrabook.com for my paypal address.

> P.S.: Whats not yet working on my kano is the built-in camera. I would be glad for anything you can point me to to get it fixed ;)

Unfortunately, these IPU webcams are a pain to get working on Linux. Your best bet would be joining the Chrultrabook Discord server for support.

**Comment by WeirdTreeThing** [comment] 2023-10-07 13:44
Closing as audio issue is fixed

**Comment by gxsw** [comment] 2023-10-09 15:16
I needed to do a fresh archlinux installation on the device. Running the script under the fresh archlinux now only makes the input audio devices working, the output devices are not availalbe and speaker don't work. Here are the debug logs:
[debug-logs.zip](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/12847764/debug-logs.zip)

**Comment by WeirdTreeThing** [comment] 2023-10-09 20:24
Your system is missing `spa-acp-tool` which means the audio log is empty. Install the `pipewire-audio` package.

**Comment by gxsw** [comment] 2023-10-10 10:55
Sorry I could have checked before... Now the logs should be there:
[debug-logs.zip](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/12856217/debug-logs.zip)

**Comment by WeirdTreeThing** [comment] 2023-10-11 00:41
Not seeing anything wrong in your logs. Just so be clear, the issue is there aren't any audio outputs in your audio settings?

**Comment by gxsw** [comment] 2023-10-11 05:56
exactly. audio there is no sound from the speakers and in the audio setting no output is showing up. (input is there)
![image](https://github.com/WeirdTreeThing/chromebook-linux-audio/assets/147204565/91ee45f6-1e3d-4c10-a13f-4701f5f27528)

**Comment by gxsw** [comment] 2023-10-11 16:21
wpctl status
PipeWire 'pipewire-0' [0.3.81, hns@kano, cookie:365274510]
 └─ Clients:
        31. xdg-desktop-portal                  [0.3.81, x@kano, pid:2241]
        32. WirePlumber                         [0.3.81, x@kano, pid:2321]
        33. WirePlumber [export]                [0.3.81, x@kano, pid:2321]
        79. wpctl                               [0.3.81, x@kano, pid:3270]

Audio
 ├─ Devices:
 │      39. sof-nau8825                         [alsa]
 │  
 ├─ Sinks:
 │      40. sof-nau8825 HDMI / DisplayPort 4 Output [vol: 1.00]
 │      41. sof-nau8825 HDMI / DisplayPort 3 Output [vol: 1.00]
 │      42. sof-nau8825 HDMI / DisplayPort 2 Output [vol: 1.00]
 │      43. sof-nau8825 HDMI / DisplayPort 1 Output [vol: 1.00]
 │      44. sof-nau8825 Headphones              [vol: 1.00]
 │  *   45. sof-nau8825 Internal Speakers       [vol: 0.40]
 │  
 ├─ Sink endpoints:
 │  
 ├─ Sources:
 │      46. sof-nau8825 Headset Microphone      [vol: 1.00]
 │      47. sof-nau8825 Internal Microphone     [vol: 1.00]
 │  *   48. sof-nau8825 n/a                     [vol: 1.00]
 │  
 ├─ Source endpoints:
 │  
 └─ Streams:

Video
 ├─ Devices:
 │  
 ├─ Sinks:
 │  
 ├─ Sink endpoints:
 │  
 ├─ Sources:
 │  
 ├─ Source endpoints:
 │  
 └─ Streams:

Settings
 └─ Default Configured Node Names:

**Comment by WeirdTreeThing** [comment] 2023-10-11 18:09
`pactl info`

**Comment by gxsw** [comment] 2023-10-11 19:23
Server String: /run/user/1000/pulse/native
Library Protocol Version: 35
Server Protocol Version: 35
Is Local: yes
Client Index: 3
Tile Size: 65472
User Name: x
Host Name: kano
Server Name: pulseaudio
Server Version: 16.1
Default Sample Specification: s16le 2ch 44100Hz
Default Channel Map: front-left,front-right
Default Sink: alsa_output.pci-0000_00_1f.3-platform-rpl_max98373_8825.HiFi__hw_sofnau8825_5__sink
Default Source: alsa_input.pci-0000_00_1f.3-platform-rpl_max98373_8825.HiFi__adl_stereo_in_sofnau8825_99_0_1__source
Cookie: e573:10f3

**Comment by gxsw** [comment] 2023-10-12 07:44
Thx!
status report:
Initially I only had pulseaudio installed. when you asked me for "wpctl status", wpctl was not available first. So I did something, that did not make sense at this point and installed the pipewire package in parallel.
Now I removed pulseaudio and replaced it by pipewire. Output was showing up then, but still no sound from the speaker.
Then I found this:
https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/787
With
/speaker-test -c 2 -t wav -l 1 -b 1024 
/
the speaker test was working.
After that I had sound from speaker in general. After a reboot I again have no sound from the speaker and speaker-test -c 2 -t wav -l 1 -b 1024 does not help anymore.

**Comment by gxsw** [comment] 2023-10-12 19:28
I was digging a little bit further into the topic:
The issue is related to an update of pipewire from 1:0.3.80 to 1:0.3.81 and/or the linux kernel from linux-6.5.5.arch1 tp linux-6.5.6.arch1, which was reaching the arch repositories on 2023-10-08.
Downgrading solves the issue and I have stable sound from the speaker again. I will just stay with pipewire 1:0.3.80 and kernel 6.5.5. for now.

**Comment by WeirdTreeThing** [comment] 2023-10-12 19:44
Oh yeah I heard about that pipewire update breaking audio for everyone.

**Comment by WeirdTreeThing** [comment] 2023-10-12 19:45
Can you try the latest kernel to see if the issue comes back?

**Comment by gxsw** [comment] 2023-10-13 13:33
yesterday a new pipewire version reached the arch repo. 
(1:0.3.81-2, https://archlinux.org/packages/extra/x86_64/pipewire/)
I updated to this one and to the latest kernel. => sound from speaker is working fine.
So the issue seems to be related to general problems in pipewire 1:0.3.81-1 and we can close it here.
Thx!

**Comment by WeirdTreeThing** [comment] 2023-10-14 16:46
Good to know

**Closed by WeirdTreeThing** 2023-10-14 16:46 UTC
