### ISSUE TITLE
Debian 12.5 - Acer C771T "Lars" - no audio

### ISSUE THREAD

**Issue by ksandbergfl** [WeirdTreeThing/chromebook-linux-audio#116] opened 2024-03-28 19:33 UTC
**Describe the bug**
I installed a fresh/new copy of Debian 12.5 (from a Live USB) onto my Acer C771T "Lars".   I installed the Chromebook audio drivers, followed the prompts, it told me everything was OK.  Reboot - no audio.   I am booting with the "chrultrabook-6.6" kernel that your script downloaded.

Previously, I was running Arch Linux on this exact same LARS, and your scripts worked OK (I had audio).  I think my Arch was at 6.1 kernel  

**Boardname**
LARS

**Logs**
DMESG shows this:
snd_soc_avs 0000:00:1f.3: Direct firmware load for intel/avs/skl/dsp_basefw.bin failed with error -2

**Comment by WeirdTreeThing** [comment] 2024-03-30 01:27
Duplicate of #117

**Closed by WeirdTreeThing** 2024-03-30 01:27 UTC
