### ISSUE TITLE
Request for .deb kernel headers 6.6.25-chrultrabook

### ISSUE THREAD

**Issue by kolotxoz** [WeirdTreeThing/chromebook-linux-audio#153] opened 2024-07-26 02:31 UTC
This is not a bug report, but rather a request, is it possible to ask for the .deb package of the kernel headers for the version "6.6.25-chrultrabook", i'm using debian, and they are needed for the use of virtualbox.

Thanks in advance

**Comment by WeirdTreeThing** [comment] 2024-07-27 17:11
Duplicate of https://github.com/chrultrabook/debian-kernel/issues/4

**Closed by WeirdTreeThing** 2024-07-27 17:11 UTC

**Comment by kolotxoz** [comment] 2024-08-01 13:48
Did'nt knew that it was a duplicate request, thx for the quick response
