### ISSUE TITLE
No audio profile Galaxy Chromebook 2 - sof-cml_max9389

### ISSUE THREAD

**Issue by MetalfaceScout** [WeirdTreeThing/chromebook-linux-audio#45] opened 2023-10-20 17:44 UTC
I'm not sure what I'm doing wrong but I can't get the audio profile to show up in GNOME. I'm on Arch Linux running the zen kernel. The audio plays with the pro profile, but only through the right speaker. 
Here's the output of 
`pactl list cards`
```Card #217
Name: alsa_card.pci-0000_00_1f.3-platform-cml_da7219_mx98357a.3
Driver: alsa
Owner Module: n/a
Properties:
api.acp.auto-port = "false"
api.acp.auto-profile = "false"
api.alsa.card = "0"
api.alsa.card.longname = "Google-Nightfury-rev7"
api.alsa.card.name = "sof-cml_max98390_da7219"
api.alsa.path = "hw:0"
api.alsa.use-acp = "true"
api.dbus.ReserveDevice1 = "Audio0"
device.api = "alsa"
device.bus = "pci"
device.bus_path = "pci-0000:00:1f.3-platform-cml_da7219_mx98357a"
device.description = "Comet Lake PCH-LP cAVS"
device.enum.api = "udev"
device.icon_name = "audio-card-analog-pci"
device.name = "alsa_card.pci-0000_00_1f.3-platform-cml_da7219_mx98357a.3"
device.nick = "sof-cml_max98390_da7219"
device.plugged.usec = "3738207"
device.product.id = "0x02c8"
device.product.name = "Comet Lake PCH-LP cAVS"
device.subsystem = "sound"
sysfs.path = "/devices/pci0000:00/0000:00:1f.3/cml_da7219_mx98357a/sound/card0"
device.vendor.id = "0x8086"
device.vendor.name = "Intel Corporation"
media.class = "Audio/Device"
factory.id = "14"
client.id = "34"
object.id = "65"
object.serial = "217"
object.path = "alsa:pcm:0"
alsa.card = "0"
alsa.card_name = "sof-cml_max98390_da7219"
alsa.long_card_name = "Google-Nightfury-rev7"
alsa.driver_name = "snd_soc_sst_bxt_da7219_max98357a"
device.string = "0"
Profiles:
off: Off (sinks: 0, sources: 0, priority: 0, available: yes)
pro-audio: Pro Audio (sinks: 5, sources: 4, priority: 1, available: yes)
Active Profile: off
```
Here's the output of a script you attached in the last Galaxy Chromebook 2 issue:
[audio-debug.log](https://github.com/WeirdTreeThing/chromebook-linux-audio/files/13057050/audio-debug.log)

Thank you for your work, and your help.

**Comment by WeirdTreeThing** [comment] 2023-10-20 18:21
Duplicate of #14, please repost your issue there.

**Closed by WeirdTreeThing** 2023-10-20 18:21 UTC
